### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by LivioGama** [pieric-ux/CashRegister#3]
This is a great work, really! Congratulations.

Here is my quick feedback for improvement and culture sharing.

The documentation is awesome and really pleasant to follow.

The email can be quite challenging to setup (not for me, I had what I needed), and, it's a blocking point because when testing, in order to access the platform, email validation is mandatory. Could be nice to bypass this when running locally, only on dev mode.

There is a small bug: after creating an app, when configuring it for the first time with no resources, the "Workstation" tab crashes. It doesn't crash anymore after creating a first workstation though.

This is really minor but an improvement could be to provide a link to a version deployed on Vercel for the non-techies :D

For the backend and the database, I strongely advise you to use a tool like [Pocketbase](https://pocketbase.io/).

It is as simple as copying in a folder and running it with a script. And then it provide a very easy and handy interface to manage the datas with a very nice SDK to manipulate it => this allow you to fully focus on your product rather than architecture/infrastructure (although of course, it is always good to know how to do the long way):

![CleanShot 2024-03-22 at 10 03 41](https://github.com/pieric-ux/CashRegister/assets/6930498/0a309364-f25e-4f94-a2c7-b8365852b4a0)

https://github.com/pieric-ux/CashRegister/assets/6930498/a80691a4-f6d8-433a-87e2-d76629d51f98

But that's not the only thing! It also adds a lot of cool features like integrated mailing configuration, S3 storage outside configuration, automated backup, easy full export import of the DB, tons of 3rd party auth provider with easy config, api request logs...

https://github.com/pieric-ux/CashRegister/assets/6930498/88527dea-3df5-45df-919f-0da719c431e6

And it handles the migrations for you:

![CleanShot 2024-03-22 at 10 12 03@2x](https://github.com/pieric-ux/CashRegister/assets/6930498/9417c4b1-c697-48d9-bc6d-86a0491f1699)

There are other nice features like the live database (like Firebase or Supabase), it is expandable and customizable, self-hosted, and open-source !

Hope you will like it as much as I do.

Cheers, and good job! 🍻

PS: For the mobile, skip React Native and go directly to [Expo](https://docs.expo.dev/versions/latest/sdk/camera/) ;)

**Comment by pieric-ux** [comment]
Hi Livio,

Thank you very much for your kind words and for taking the time to provide such detailed feedback on my project. I truly appreciate it!

Regarding the email setup, I completely understand your point about its complexity, especially for non-technical users. To address this, I've implemented a Docker-based solution, incorporating a mailplit container. While considering email validation, particularly during employee creation, it became evident that a mail server is indispensable even for local testing. Hence, Docker seemed the most straightforward approach to tackle this issue. I'll see if I can make it even better.

I'd like to express my gratitude for highlighting the deployment option on Vercel. Indeed, the site is already live at [cashregister.ch](https://cashregister.ch/) although I haven't yet documented it extensively as the project is still in its developmental phase.

Your recommendation for Pocketbase is greatly appreciated. It's a project that I hadn't previously encountered, and it certainly seems promising. While Laravel was the chosen backend for this project due to curriculum requirements, Pocketbase has certainly piqued my interest for future endeavors.

On the subject of mobile development, I'm currently focused on creating iOS and Android apps using React Native. After initially starting with React Native CLI, I swiftly transitioned to Expo Bare and have since shifted my focus primarily to the mobile aspect of the project. My goal is to deliver a packaged Web iOS and Android solution promptly to meet user requirements. Subsequently, I plan to continue enhancing my project by adding new features and addressing any remaining bugs on the web version.

Additionally, thank you for bringing the bug in the "Workstation" tab to my attention. I've addressed this issue in commit 01b2e28 with the message "Fix: dashboard tabs without workstations".

Your feedback is immensely valuable, and I'm truly grateful for your contribution to the project's improvement.

Best regards,
Demont Pieric

**Comment by LivioGama** [comment]
I recently made a short video (less than 8 min) on how to get started with PocketBase with two inner join collections, authentication and CRUD on it. 

Enjoy https://drive.google.com/file/d/1blhi_JTQ91T-6oDtWcVKtPbArQEGu79Z/view?usp=sharing

Stack:
- Pocketbase (for the DB)
- Expo (for the cross-platform application)
- React Query (for caching, retry policy and query orchestration)
- Legendapp state (for the state in memory and persisted in the app)
